### ISSUE TITLE
LMCMAES plotting: Error when plotting tutorial advanced/4

### ISSUE THREAD

**Issue by sunsibar** [cselab/korali#432]
Branch: Master
Steps to reproduce:
```
# install Korali
cd tutorials/advanced/4.running.cxx/
make
./run-lmcma 
python3 -m korali.plotter 
```

I'm getting the error: 

```
:1
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/noobuntu/.local/lib/python3.6/site-packages/korali/plotter/__main__.py", line 150, in <module>
    main(args.dir, args.check, args.test, args.output, args)
  File "/home/noobuntu/.local/lib/python3.6/site-packages/korali/plotter/__main__.py", line 96, in main
    solverLib.plot(genList, args)
  File "/home/noobuntu/.local/lib/python3.6/site-packages/korali/plotter/../modules/solver//LMCMAES/LMCMAES.py", line 41, in plot
    'Maximum Covariance Eigenvalue'] / genList[gen]['Solver'][
KeyError: 'Maximum Covariance Eigenvalue'
```
Same for lmcmaes-direct. The others in tutorial 4 work fine.

**Comment by SergioMartin86** [comment]
This has been solves in the master branch I think. Can you confirm?

**Comment by gtarabat** [comment]
Considered fixed.
